- name: Install k8s and docker packages
  become: yes
  hosts: servers
  roles:
    - docker
    - k8s-all

- name: Setup control plane node
  become: yes
  hosts: kubernetes_master
  roles:
    - k8s-master

- name: Setup worker node
  become: yes
  hosts: kubernetes_worker
  roles:
    - k8s-worker