- name: generate new token
  command: kubeadm token create --print-join-command
  register: kubeadm_init_output

- name: Create file with output
  copy:
    content: "{{ kubeadm_init_output.stdout }}"
    dest: /root/kubeadminit

- name: Prepare kubejoin script
  shell: tail -2 /root/kubeadminit > /root/kubejoin.sh

- name: Get kubejoin
  fetch:
    dest: ./join
    src: /root/kubejoin.sh
    
- name: Organize files
  shell: |
        cp join/{{ inventory_hostname }}/root/kubejoin.sh join/  
        rm -fr join/{{ inventory_hostname }}
  delegate_to: localhost
  become: no